name: quickbite_campus
description: Fast & Easy Campus Food Ordering System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  provider: ^6.1.1
  cupertino_icons: ^1.0.6
  cloudinary: ^1.2.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  fl_chart: ^0.69.2
  intl: ^0.20.1
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/app_logo.png
    - .env
    - assets/images/signup.svg
    - assets/images/login.svg