// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU11SS6RlYHk2BYDWN__R-xcHSV_k2jco',
    appId: '1:718526136551:web:71ea43f11d351b76dc6242',
    messagingSenderId: '718526136551',
    projectId: 'unicanteenvirtualqueue',
    authDomain: 'unicanteenvirtualqueue.firebaseapp.com',
    storageBucket: 'unicanteenvirtualqueue.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5VyBcW7ZMtzBjyJnLMh0_VuVPMUR7cKY',
    appId: '1:718526136551:android:359b4a8880f2e250dc6242',
    messagingSenderId: '718526136551',
    projectId: 'unicanteenvirtualqueue',
    storageBucket: 'unicanteenvirtualqueue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj6_BrgyoRiIkRtdVHflvMYq9SdlTrXTA',
    appId: '1:718526136551:ios:77310025b08f7f10dc6242',
    messagingSenderId: '718526136551',
    projectId: 'unicanteenvirtualqueue',
    storageBucket: 'unicanteenvirtualqueue.firebasestorage.app',
    iosBundleId: 'com.uniqueue.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj6_BrgyoRiIkRtdVHflvMYq9SdlTrXTA',
    appId: '1:718526136551:ios:19bcb17c31106d5adc6242',
    messagingSenderId: '718526136551',
    projectId: 'unicanteenvirtualqueue',
    storageBucket: 'unicanteenvirtualqueue.firebasestorage.app',
    iosBundleId: 'com.uniqueu.app',
  );
}
